# Generated by Django 4.2 on 2023-06-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_appuser_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
