# Generated by Django 4.2 on 2024-02-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_labels_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
