# Generated by Django 4.2 on 2023-05-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0002_alter_tasks_author_alter_tasks_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='labels',
            field=models.ManyToManyField(to='labels.labels'),
        ),
    ]
