# Generated by Django 4.2 on 2024-02-09 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_rename_labels_label'),
        ('users', '0004_initial'),
        ('statuses', '0002_rename_statuses_status'),
        ('tasks', '0004_alter_tasks_author_alter_tasks_executor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
